-- Contenu initial : édition à venir et archives reprises de l'ancien site foulees.samparis12.org.
-- Idempotent : chaque ligne est identifiée par une clé unique (année, ordre), INSERT IGNORE ne la recrée pas.

INSERT IGNORE INTO editions (annee, numero, date_course, titre, texte, inscription_url, horaires_reference, option_chimps) VALUES (2027, 22, '2027-06-13', '', '', '', 2026, '+18 €');
INSERT IGNORE INTO edition_departs (edition_id, ordre, heure, course, detail, prix) SELECT id, 1, '8h45', '5 km', 'Une boucle autour du lac Daumesnil', 'À partir de 10 €' FROM editions WHERE annee = 2027;
INSERT IGNORE INTO edition_departs (edition_id, ordre, heure, course, detail, prix) SELECT id, 2, '9h30', '10 km', 'Deux boucles, sas et meneurs d’allure', 'À partir de 18 €' FROM editions WHERE annee = 2027;
INSERT IGNORE INTO edition_departs (edition_id, ordre, heure, course, detail, prix) SELECT id, 3, '11h00', 'Kid’s 1 000 m', '7 à 9 ans, dans le vélodrome', '5 €' FROM editions WHERE annee = 2027;
INSERT IGNORE INTO edition_departs (edition_id, ordre, heure, course, detail, prix) SELECT id, 4, '11h15', 'Kid’s 1 500 m', '10 et 11 ans, dans le vélodrome', '5 €' FROM editions WHERE annee = 2027;
INSERT IGNORE INTO edition_retraits (edition_id, ordre, jour, horaire, lieu) SELECT id, 1, 'Vendredi', '15h – 20h', 'Stade Léo Lagrange, Porte de Charenton' FROM editions WHERE annee = 2027;
INSERT IGNORE INTO edition_retraits (edition_id, ordre, jour, horaire, lieu) SELECT id, 2, 'Samedi', '10h – 18h', 'Vélodrome Jacques Anquetil « La Cipale », 51 avenue de Gravelle' FROM editions WHERE annee = 2027;
INSERT IGNORE INTO edition_retraits (edition_id, ordre, jour, horaire, lieu) SELECT id, 3, 'Dimanche', 'Pas de retrait', 'Les dossards se retirent la veille au plus tard' FROM editions WHERE annee = 2027;

-- Édition 2026
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2026, '2026-06-14', '21e édition, 250 bénévoles', '', 'https://www.protiming.fr/Results/runningR/8025-Les-Foulees-du-12eme/6');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, 'Bénévoles' FROM editions WHERE annee = 2026;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, '250 bénévoles mobilisés', 'https://photos.app.goo.gl/shDfPur6QDCgTCxbA' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 1;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 2, '5 km' FROM editions WHERE annee = 2026;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Photos de la course', 'https://photos.app.goo.gl/hRCquZhfzSipWt6b9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Photos de l''arrivée', 'https://photos.app.goo.gl/nJLFJMHuXSdjm4Vq6' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Vidéo', 'https://www.instagram.com/sam_paris_12/reel/DZksN6UMqVA/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 2;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 3, '10 km' FROM editions WHERE annee = 2026;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Photos ambiance', 'https://photos.app.goo.gl/1SdWGzcmxZxcHrnL7' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Photos de la course', 'https://photos.app.goo.gl/z925t1Sn5rCbdCjC9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Photos de l''arrivée', 'https://photos.app.goo.gl/SzNMhZFrkUay7Chc7' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Photos des podiums', 'https://photos.app.goo.gl/o6grAo7gBvduikYA9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 5, 'Vidéo', 'https://www.instagram.com/reels/DZkwBxasXx1/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 3;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 4, 'I Run for Chimps' FROM editions WHERE annee = 2026;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Photos de Jean-Michel Krief', 'https://photos.app.goo.gl/LVW4M8t4mB3kDMaN9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 4;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 5, 'Kid''s Foulées' FROM editions WHERE annee = 2026;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, '1 000 m · course et podium', 'https://photos.app.goo.gl/mwF8sSxrkGpK6gi27' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 5;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, '1 000 m · ligne d''arrivée', 'https://photos.app.goo.gl/i42s2ex6QZHwBxVS6' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 5;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, '1 500 m · course et podium', 'https://photos.app.goo.gl/ENoNm1Vr2fX9jbNCA' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 5;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, '1 500 m · ligne d''arrivée', 'https://photos.app.goo.gl/65w2MbCGjD2q9HDf9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 5;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 6, 'Photographes hors SAM' FROM editions WHERE annee = 2026;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'GiaoRunning · départ', 'https://www.facebook.com/share/p/1CbMdjg3K3/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 6;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'GiaoRunning · la course 1', 'https://www.facebook.com/share/p/1D6XHvr7ab/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 6;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'GiaoRunning · la course 2', 'https://www.facebook.com/share/1CMtFuJahD/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 6;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'GiaoRunning · arrivée', 'https://www.facebook.com/share/p/183utpPXZU/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 6;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 5, 'Farhay · 5 km', 'https://www.facebook.com/media/set/?set=a.122162886716716763&type=3' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 6;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 6, 'Farhay · 10 km, partie 1', 'https://www.facebook.com/media/set/?set=a.122162920772716763&type=3' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 6;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 7, 'Farhay · 10 km, partie 2', 'https://www.facebook.com/profile.php?id=61571502908473' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2026 AND g.ordre = 6;

-- Édition 2025
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2025, NULL, '20e édition', '', 'https://www.protiming.fr/Results/runningR/7410-Les-Foulees-du-12eme/6');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, 'Photos de l''arrivée' FROM editions WHERE annee = 2025;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, '5 km', 'https://photos.app.goo.gl/m1ZvJUssjeXhvKau9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, '10 km', 'https://photos.app.goo.gl/hNE5Rckka2nmu9AG9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Kid''s 1 000 m', 'https://photos.app.goo.gl/LHZ3nSfAPjCrUWav9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Kid''s 1 500 m', 'https://photos.app.goo.gl/SXWZ5s6MVBg4XCDW7' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 1;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 2, 'Albums des photographes' FROM editions WHERE annee = 2025;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Jean-Pierre · 10 km', 'https://photos.app.goo.gl/WWZtTPnkSTwu7C3z7' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'GiaoRunning · 10 km, départ', 'https://www.facebook.com/media/set/?set=a.1172493844918074&type=3' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'GiaoRunning · 10 km, 1re partie', 'https://www.facebook.com/share/p/1LyvuKK4Z1/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'GiaoRunning · 10 km, 2e partie', 'https://www.facebook.com/media/set/?set=a.1172510448249747&type=3' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 5, 'Farhay Photographies', 'https://www.facebook.com/media/set/?vanity=61571502908473&set=a.122129645702716763' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 6, 'Laurent', 'https://drive.google.com/drive/folders/1A3SIH5VenshR9PtQlN8gDDIJCMZDAeGf' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 7, 'Julien', 'https://photos.google.com/share/AF1QipN4jSqx0-khbGxg15jRuG4vckghRWMjEPXg2vuPRdWHDDmHXkfk-dRA1ztX8cdaow?pli=1&key=MTZDTnhzN1JvdENPZmR2R3Z6YU01UVF5ZmdIV3BR' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 8, 'Amaury', 'https://photos.app.goo.gl/MdNQnTKeeswQvWBC9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 2;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 3, 'Vidéos des départs' FROM editions WHERE annee = 2025;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, '5 km · ligne de départ', 'https://samparis12.org/video/Foulees2025/Before5km.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, '5 km · départ', 'https://samparis12.org/video/Foulees2025/Start5km2.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, '10 km · ligne de départ', 'https://samparis12.org/video/Foulees2025/Before10km.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, '10 km · départ', 'https://samparis12.org/video/Foulees2025/Start10km2.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 5, '10 km · vague élite', 'https://samparis12.org/video/Foulees2025/10kmDepartVagueElite.mp4' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 6, '10 km · vague 40 – 45 min', 'https://samparis12.org/video/Foulees2025/10kmDepartVague40mn.mp4' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 7, '10 km · vague 50 min', 'https://samparis12.org/video/Foulees2025/10kmDepartVague50mn.mp4' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 8, '10 km · vague 55 min', 'https://samparis12.org/video/Foulees2025/10kmDepartVague55mn.mp4' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 9, 'Kid''s 1 000 m · départ', 'https://samparis12.org/video/Foulees2025/Start1000m2.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 10, 'Kid''s 1 500 m · départ', 'https://samparis12.org/video/Foulees2025/Start1500m2.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 3;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 4, 'Vidéos de l''arrivée du 10 km (meneurs d''allure)' FROM editions WHERE annee = 2025;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Flamme 45 min', 'https://samparis12.org/video/Foulees2025/Finish10km45.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 4;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Flamme 50 min', 'https://samparis12.org/video/Foulees2025/Finish10km50.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 4;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Flamme 55 min', 'https://samparis12.org/video/Foulees2025/Finish10km55.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 4;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Flamme 60 min', 'https://samparis12.org/video/Foulees2025/Finish10km60.mov' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2025 AND g.ordre = 4;

-- Édition 2024
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2024, NULL, '19e édition', '', 'https://protiming.fr/Results/runningR/6941-Les-Foulees-du-12eme/6');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, 'Albums photos' FROM editions WHERE annee = 2024;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Les coureurs, par Fred', 'https://photos.app.goo.gl/6nkNojAH3ogqmF966' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2024 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Les coureurs, par Farhay Photographie', 'https://www.facebook.com/share/p/5TptiFGf2v8JDd1J/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2024 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'La course des enfants, par Fred', 'https://photos.google.com/share/AF1QipOu79Lxrx2k-LsXItmZWhVdsHUEkY8QO8MptrmA0xJsZG3zDzjVOb4chGHDi2pYQQ?key=WTB1YWVEcEs3RTk3eGhTVlNndnk1N1NhR2JKWVZB' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2024 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Les bénévoles, par Amaury', 'https://photos.app.goo.gl/bK3Fuhv4dzgbnioQ7' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2024 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 5, 'Les bénévoles, par Fred', 'https://photos.google.com/share/AF1QipP5S0ocqCh9-JO-PuQPAHZEroHsEd-1HxyuzigukhZIc9B5MIgJClbsS3K5jPlelw?key=U0lJQjJyZk5FUkpwSlY3bktfRVlKcFFSR09OYndB' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2024 AND g.ordre = 1;

-- Édition 2023
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2023, NULL, 'Triple record', 'Record de participation (1 296 inscrits, 1 075 classés) et records de l''épreuve chez les hommes, Luc Montaudon en 30''25", et chez les femmes, Méline Rollin en 33''37".', 'https://protiming.fr/Results/runningR/6417/6');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, '10 km' FROM editions WHERE annee = 2023;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Jean-Pierre', 'https://photos.app.goo.gl/obSgTM74Sdd7DJqB6' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Karim', 'https://photos.google.com/share/AF1QipMXheEPwRoCGPgkdJHKCbP74C7PRz24-hevuUUZBXTy09_9LGrkYex3lf1lUYVaDA?key=THlYaVJWQ2NDM19IWGlUZXhyT3VEbURRQ01ub2NR' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Jean', 'https://photos.app.goo.gl/SLgBKJXZTKd3eqd27' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Jean-Michel (10 km et Kid''s)', 'https://photos.app.goo.gl/i8vWGLLkbikKMkBn9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 5, 'Farhay Photographie', 'https://m.facebook.com/story.php?story_fbid=646002534241165&id=100064942712070' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 6, 'Fred, partie 1', 'https://photos.google.com/share/AF1QipOwR4NJxGPNND8yvrL0Ze76dqh-jzvP5WKB5I15oYhVCrd8bDrBwk_qt7HUILuB1A?key=VXhnZHVGbGk2dHVTVVR2VThfc2hROWdNRHVPcUlR' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 7, 'Fred, partie 2', 'https://photos.google.com/share/AF1QipNzUEMYGBppaaQ0QZMusWBfTgWOr81NX89q021mMr5DAZ46Bu0TB9yFqImzxlvSAA?key=RzJZRXo5ODlmSzFZdTZpbTBocUxyU05EM2ltYV93' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 8, 'Fred, partie 3', 'https://photos.google.com/share/AF1QipORv0QYy8R6T__FPCE93ZRmkqjg0jUmwDgolJ7-9uHrAAoEmlFzXyA6B5-igtuQqw?key=TjEtNXBLelhHQTdBWENrSHFvMUI4UmFPQ0JsVnRR' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 1;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 2, 'Kid''s Foulées' FROM editions WHERE annee = 2023;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Karim', 'https://photos.google.com/share/AF1QipN9xtYJL9RM-MANTKam-J5eq9MIoBl7IRjmcUONSP19cMaxSO3Lyr_j6bEuR5d5uA?key=aG02aVgxeFk5MHpGT0N6alMyUVc1bU5TQmY1cFdn' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Fred', 'https://photos.google.com/share/AF1QipOLyb80G6VXvH95HB6PJvkYg0UbuQU08dfB5PGKM_hRqquG4sOurc44Ll-wuL9ayQ?key=S2FxUE9ndXJsczQwN0h1M1paNkY4dW1aaUllNU5B' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2023 AND g.ordre = 2;

-- Édition 2022
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2022, NULL, '', '', 'https://protiming.fr/Results/runningR/6193/6');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, 'Albums photos' FROM editions WHERE annee = 2022;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Tous les arrivants', 'https://photos.google.com/share/AF1QipMbM9PocYukMK3aVeGszI7nNgv2p4Izcll3EMuxN1IsGXcFUiDZckAHjQgWb6NS1A?key=bjUzOVRXakFmbnNvZ3FJY0M4TzFpcXktT3dNNU5R' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Sur le parcours, par Jean-Pierre', 'https://photos.app.goo.gl/pDhiXBJKjoicagm89' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Derniers préparatifs, par Ronan David Assa', 'https://nis.nikonimagespace.com/html/guest/fr/index.html?g=FoP1YTjKujGzAomEh5OwHEXGPSrDUkPLYMGsxxRMWGGx3SejEbQaqDEn1DSwev3Z5Tn5G-vXSoc15gBck_DdqQ#grid' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Sur le parcours, par Ronan David Assa', 'https://nis.nikonimagespace.com/html/guest/fr/index.html?g=FoP1YTjKujGzAomEh5OwHEXGPSrDUkPLJr4GhISo3L2x3SejEbQaqDEn1DSwev3Z5Tn5G-vXSoc15gBck_DdqQ#grid' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 5, 'Sur le vélodrome, par Ronan David Assa', 'https://nis.nikonimagespace.com/html/guest/fr/index.html?g=FoP1YTjKujGzAomEh5OwHEXGPSrDUkPL6aEI29E-2WGx3SejEbQaqDEn1DSwev3Z5Tn5G-vXSoc15gBck_DdqQ&p=3#grid' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 6, 'Course des enfants, par Ronan David Assa', 'https://nis.nikonimagespace.com/html/guest/fr/index.html?g=FoP1YTjKujGzAomEh5OwHEXGPSrDUkPLX24CFixUT2Kx3SejEbQaqDEn1DSwev3Z5Tn5G-vXSoc15gBck_DdqQ&p=2#grid' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 7, 'Courses enfants', 'https://drive.google.com/drive/folders/1pbVJB_rzEeqtXBncE8Kfph93f5aJaVUS' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 8, 'I Run for Chimps, par Jean-Michel', 'https://photos.google.com/share/AF1QipO4jyf9xnAl3jF6b_DFbAFgMH0IzEGcYCb8deBNXplRHcMdVn1ymxBOtQV8oO4f1A?key=eDdtaVlJdTlKZU82VTVUNUgyYzNkcTl6bkdHSktB' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 1;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 2, 'Vidéos (Immersion 360)' FROM editions WHERE annee = 2022;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Vidéo 1 de la course', 'https://www.instagram.com/reel/Cet_i9Plr-e/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Vidéo 2 de la course', 'https://www.instagram.com/reel/CeuAUk4lJwZ/' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2022 AND g.ordre = 2;

-- Édition 2019
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2019, NULL, '1 200 coureurs, dont 200 pour les chimpanzés', '', 'https://bases.athle.fr/asp.net/liste.aspx?frmbase=resultats&frmmode=1&frmespace=0&frmcompetition=219221');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, 'Le long du lac, vers le zoo (Jean-Pierre)' FROM editions WHERE annee = 2019;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Album 1 · les premiers', 'https://photos.app.goo.gl/Uk2qf7gpQKx2wTgo6' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Album 2 · les suivants', 'https://photos.app.goo.gl/AqepsksPyCyUnKPB9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Album 3', 'https://photos.app.goo.gl/fBZuf4RcUHZieiC67' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 1;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 2, 'Départ, parcours et arrivée' FROM editions WHERE annee = 2019;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Alain · départ et parcours', 'https://photos.google.com/share/AF1QipMcziNRnsaksTr5Rm9D7DqERPi5li6dR3Y3A28hx-W3gB_wNdvfJGtcCUVcHz_-QQ?key=QURXUHV6Y1F5bWNLeGZVUzkxeERkVlVXRzREZ0VR' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Fred · départ et km 4,5', 'https://photos.google.com/share/AF1QipNuuJjKh4sxvgGRKSg_BqCm4T29FnNWd5Q8CkfWPfXFLbNQB1ZriGngfkWFym-ZKA?key=SnpUenQxUHNQNDN2ZEVsUEhJVmtRSDhxUjU3UU5R' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Fred · tous les coureurs à l''arrivée', 'https://photos.google.com/share/AF1QipM2Pq4pukUpNS772zslXvk_Vdsq9tIWRIHQUSIJYobs4Z9vM1JjUvnJd0Oxt2v0hA?key=NlZONzdPald3U0ZzbTdERTJzVlBKcDh1MlBucEh3' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 2;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Jean-Michel · I Run for Chimps', 'https://photos.google.com/share/AF1QipNNNAqd9ohIs9ALHh6hT7mTOmdYHBiABcaVDz_0f39aDBi9PLbEb6co1tdZKD6YVQ?key=cnZCODhReEdGZGcyRGdvZG1BR0RJaTdwTDE4VTNR' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 2;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 3, 'Kid''s Foulées' FROM editions WHERE annee = 2019;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Thierry · l''échauffement', 'https://photos.google.com/share/AF1QipMsOu66EiY8VCIbYgGvBzoOBBSnThZ0UV1_ozJz6C0I2T78h5_4TIE1VBG72CqwXA?key=TVNnZGZKbl90N2FCN0VzTzRXSTNsMThMTzJOSGln' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Thierry · nés en 2010 – 2012', 'https://photos.google.com/share/AF1QipMIwudt21074lxxsxOlPXY7SCsirX8RvG4g5XKi-VTo7_LSLb6HMBOLobJWISV1EA?key=a1p5Z2Y5UUg2V3Zvd0I1Y2JRWGNQR0tQX3BkTnBn' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Thierry · nés en 2008 – 2009', 'https://photos.google.com/share/AF1QipPXKv3ocvnbyD0_cuT4BSdjHxo5Kze6jVBXBBZfIEflnddUNgftgaGXq5NXqwgtKA?key=dVE1VXNLLXFob3NQa2o4VmN3elFEUktqUXF3MVRR' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 3;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Fred · la course des enfants', 'https://photos.google.com/share/AF1QipMfhXeGaD-V3b2pd4bJKnGqzmZJPOTlhYsl9CJjUvcUUP9dtjPGgWR5jL2ceiT0Ww?key=cGFnRzBobDJxMTBjenAyVkFDOGxlcGRXUk0tNGZn' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2019 AND g.ordre = 3;

-- Édition 2018
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2018, NULL, '', '', 'https://bases.athle.fr/asp.net/liste.aspx?frmbase=resultats&frmmode=1&frmespace=0&frmcompetition=205185');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, 'Albums photos' FROM editions WHERE annee = 2018;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Philippe · départ et arrivée', 'https://durand-photos.mycozy.cloud/public?sharecode=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGFyZSIsImlhdCI6MTUyOTIzOTY4NywiaXNzIjoiZHVyYW5kLm15Y296eS5jbG91ZCIsInN1YiI6ImVtYWlsIn0.7OxT212fcd_3o3UP8P0wTvu95HvaAuXxJAY0ejRhHBLiDPWxQZF-wxZR_tB2zk2QobUWmXzGTSi-PG4mAguZ6Q&id=ff35b1e4eb9a5ad20c9ffda708283fe1#/shared/ff35b1e4eb9a5ad20c9ffda708283fe1' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2018 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Viet · sur le parcours', 'https://photos.app.goo.gl/GJWFRkJ22DwQwBJv9' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2018 AND g.ordre = 1;

-- Édition 2017
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2017, NULL, '', '', '');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, 'Albums photos' FROM editions WHERE annee = 2017;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'Album 1 · F. Bougrain', 'https://photos.google.com/u/0/share/AF1QipMNf0K8aWGQHcYvN6c5Y0ruoYxN8bajC9Oh3D73TQdSUl3JEHEnM2MXxfcRPmJgrQ?key=REtRc2tZVlpjN2dlekZtYkNGTTBoMTEzSmMwak9R' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 2, 'Album 2 · ligne d''arrivée', 'https://goo.gl/photos/rmYAHmtUMAT8mP1S8' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 3, 'Album 3 · JP Chabane', 'https://goo.gl/photos/NmPKv7pCKqZVAehV7' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 4, 'Album 4 · F. Bougrain', 'https://photos.google.com/u/0/share/AF1QipNjNieBamvZWnsgP1BaZL1hkWxWfPaSeQxXdGuwMaC6H7odPLSNN3VDLwv7aSrS3Q?key=MjNZdHhmVEktUXhwemotSWk5WFpFRVZaRlJjM29R' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 5, 'Album 5 · JM Krief', 'https://goo.gl/photos/QqAEn4T4dco7wJir8' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 6, 'Le départ · R. Vidal', 'https://goo.gl/photos/7wZAMSMdBJ8XVmtMA' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 7, 'Le 6e km · R. Vidal', 'https://goo.gl/photos/4dmTtJybV7c9KnkR6' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 1;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 8, 'L''arrivée · R. Vidal', 'https://goo.gl/photos/aHs6WXDufbjKgc7T8' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 1;
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 2, 'Vidéo' FROM editions WHERE annee = 2017;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'La course, par Julien Achard', 'https://vimeo.com/223950633' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2017 AND g.ordre = 2;

-- Édition 2016
INSERT IGNORE INTO editions (annee, date_course, titre, texte, resultats_url) VALUES (2016, NULL, '', '', '');
INSERT IGNORE INTO edition_groupes (edition_id, ordre, titre) SELECT id, 1, 'Albums photos' FROM editions WHERE annee = 2016;
INSERT IGNORE INTO edition_liens (groupe_id, ordre, label, href) SELECT g.id, 1, 'La course et l''arrivée sur la Cipale', 'https://photos.google.com/share/AF1QipPG8kDsV1DfuhxVgsvlUyfCg_OSbyAAY7TdnTNHT04-5lD_RVqDRWddp2t9N6RqYA/photo/AF1QipN_Ec6CDWpQfAwm4odMZxdXx37wH5owC2qS5_sC?key=NVM0NWdSQjhob09tQVFxVGRnUkI2X3drcGQ2UG13' FROM edition_groupes g JOIN editions e ON e.id = g.edition_id WHERE e.annee = 2016 AND g.ordre = 1;
